[package]
name = "kayak_ui"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = ["bevy_kayak_ui", "kayak_core", "kayak_render_macros", "kayak_font"]

[features]
default = ["bevy_renderer"]
bevy_renderer = [
    "bevy_kayak_ui",
    "kayak_font/bevy_renderer",
    "kayak_core/bevy_renderer",
    "bevy",
]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "9a16a4d01830297987db40b45f03382ed3acad62", optional = true }
kayak_core = { path = "kayak_core" }
bevy_kayak_ui = { path = "bevy_kayak_ui", optional = true }
kayak_font = { path = "kayak_font" }
kayak_render_macros = { path = "kayak_render_macros" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "9a16a4d01830297987db40b45f03382ed3acad62" }

[[example]]
name = "todo"
path = "examples/todo/todo.rs"
